config/routes.rb
Facturas::Application.routes.draw do
  resources :articulos_facturas

  resources :sucursals

  resources :facturas

  resources :clientes

  resources :articulos

  get "sesion/sesion"

  get "registro/registro"

  get "inicio/index"

  get "facturas/descarga_pdf/:id", :controller => :facturas, :action => :descarga_pdf

  match "factura/facturar" => "facturas#facturar", :as => :vista_previa, :via => :get

  devise_for :users, :controllers => { registrations: 'registro', sessions: 'sesion' }

  root :to => 'inicio#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :user
  has_many :facturas

  attr_accessible :nombre, :rfc, :calle, :numexterno, :numinterno, :colonia, :codpostal, :delegacion, :ciudad, :estado
  
  validates_presence_of :nombre, :message => "no puede estar vacío."
  validates_presence_of :rfc, :message => "no puede estar vacío."
  validates_presence_of :calle, :message => "no puede estar vacío."
  validates_presence_of :numexterno, :message => "no puede estar vacío."
  validates_presence_of :colonia, :message => "no puede estar vacío."
  validates_presence_of :codpostal, :message => "no puede estar vacío."
  validates_presence_of :delegacion, :message => "no puede estar vacío."
  validates_presence_of :ciudad, :message => "no puede estar vacío."
  validates_presence_of :estado, :message => "no puede estar vacío."
  validates_format_of :codpostal, :with => /\A\d{0,5}\Z/, :on => :create, :message => "no tiene un formato válido." 
  def to_label
    "#{nombre}"
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.json
  before_filter :authenticate_user!
  def index
    @clientes = Cliente.all
    @clientes = current_user.clientes
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new
    @cliente = current_user.clientes.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])
    @cliente.user_id = current_user.id

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente añadido exitosamente.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente modificado con éxito.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.es.html.erb
<%= simple_form_for(@cliente) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre, :label => 'Nombre'%>
    <%= f.input :rfc, :label => 'RFC'%>
    <%= f.input :calle, :label => 'Calle' %>
    <%= f.input :numexterno, :label => 'Número exterior' %>
    <%= f.input :numinterno, :label => 'Número interior', :hint => 'De existir' %>
    <%= f.input :colonia, :label => 'Colonia' %>
    <%= f.input :codpostal, :label => 'Código postal' %>
    <%= f.input :delegacion, :label => 'Delegación/Municipio' %>
    <%= f.input :ciudad, :label => 'Ciudad' %>
    <%= f.input :estado, :label => 'Estado' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/clientes/edit.es.html.erb
<h2>Editar datos de cliente</h2>

<%= render 'form' %>

<%= link_to 'Mostrar', @cliente %> |
<%= link_to 'Regresar', clientes_path %>

app/views/clientes/index.es.html.erb
<h1>Cartera de clientes</h1>

<table class="table table-hover">
  <tr>
    <th>Nombre</th>
    <th>Rfc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nombre %></td>
    <td><%= cliente.rfc %></td>

    <td><%= link_to 'Mostrar', cliente %></td>
    <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Eliminar', cliente, confirm: '¿Está seguro(a)?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Añadir cliente', new_cliente_path %>

app/views/clientes/new.es.html.erb
<h2>Añadir cliente</h2>

<%= render 'form' %>

<%= link_to 'Regresar', clientes_path %>

app/views/clientes/show.es.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @cliente.nombre %>
</p>

<p>
  <b>Rfc:</b>
  <%= @cliente.rfc %>
</p>

<p>
  <b>Calle:</b>
  <%= @cliente.calle %>
</p>

<p>
  <b>Numexterno:</b>
  <%= @cliente.numexterno %>
</p>

<p>
  <b>Numinterno:</b>
  <%= @cliente.numinterno %>
</p>

<p>
  <b>Colonia:</b>
  <%= @cliente.colonia %>
</p>

<p>
  <b>Codpostal:</b>
  <%= @cliente.codpostal %>
</p>

<p>
  <b>Delegacion:</b>
  <%= @cliente.delegacion %>
</p>

<p>
  <b>Ciudad:</b>
  <%= @cliente.ciudad %>
</p>

<p>
  <b>Estado:</b>
  <%= @cliente.estado %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>