config/routes.rb
Facturas::Application.routes.draw do
  resources :articulos_facturas

  resources :sucursals

  resources :facturas

  resources :clientes

  resources :articulos

  get "sesion/sesion"

  get "registro/registro"

  get "inicio/index"

  get "facturas/descarga_pdf/:id", :controller => :facturas, :action => :descarga_pdf

  match "factura/facturar" => "facturas#facturar", :as => :vista_previa, :via => :get

  devise_for :users, :controllers => { registrations: 'registro', sessions: 'sesion' }

  root :to => 'inicio#index'

end

app/models/articulos_factura.rb
class ArticulosFactura < ActiveRecord::Base

   belongs_to :articulo
   belongs_to :user

   attr_accessible :articulo_id,:cantidad, :tags_attributes

   validates_presence_of :articulo_id
   validates_presence_of :cantidad, :message => "No puede estar vacío."
   validates_numericality_of :cantidad, :greater_than => 0, :message => "debe ser un valor numérico mayor que 0."
end

app/controllers/articulos_facturas_controller.rb
class ArticulosFacturasController < ApplicationController
  # GET /articulos_facturas
  # GET /articulos_facturas.json
  before_filter :authenticate_user!
  def index
    @articulos_facturas = ArticulosFactura.joins(:articulo,:user).where(:ip_cliente => request.remote_ip,:user_id => current_user.id)
    @articulos = Articulo.joins(:articulos_facturas).where("articulos_facturas.ip_cliente" => request.remote_ip)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articulos_facturas }
    end
  end

  # GET /articulos_facturas/1
  # GET /articulos_facturas/1.json
  def show
    @articulos_factura = ArticulosFactura.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @articulos_factura }
    end
  end

  # GET /articulos_facturas/new
  # GET /articulos_facturas/new.json
  def new
    @articulos_factura = ArticulosFactura.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @articulos_factura }
    end
  end

  # GET /articulos_facturas/1/edit
  def edit
    @articulos_factura = ArticulosFactura.find(params[:id])
  end

  # POST /articulos_facturas
  # POST /articulos_facturas.json
  def create
    @articulos_factura = ArticulosFactura.new(params[:articulos_factura])
    @articulos_factura.ip_cliente = request.remote_ip
    @articulos_factura.user_id = current_user.id

    respond_to do |format|
      if @articulos_factura.save
        format.html { redirect_to @articulos_factura, notice: 'Articulo añadido a la factura exitosamente.' }
        format.json { render json: @articulos_factura, status: :created, location: @articulos_factura }
      else
        format.html { render action: "new" }
        format.json { render json: @articulos_factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articulos_facturas/1
  # PUT /articulos_facturas/1.json
  def update
    @articulos_factura = ArticulosFactura.find(params[:id])

    respond_to do |format|
      if @articulos_factura.update_attributes(params[:articulos_factura])
        format.html { redirect_to @articulos_factura, notice: 'Articulo modificado exitosamente para facturar.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @articulos_factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos_facturas/1
  # DELETE /articulos_facturas/1.json
  def destroy
    @articulos_factura = ArticulosFactura.find(params[:id])
    @articulos_factura.destroy

    respond_to do |format|
      format.html { redirect_to articulos_facturas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articulos_facturas_helper.rb
module ArticulosFacturasHelper
end

app/views/articulos_facturas/_form.es.html.erb
<%= simple_form_for(@articulos_factura) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :articulo, collection: User.find(current_user.id).articulos, include_blank: false %>
    <%= f.input :precio_u, :label => 'Precio unitario' %>
    <%= f.input :cantidad, :label => 'Cantidad' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/articulos_facturas/edit.es.html.erb
<h2>Editar artículo a añadir a la factura</h2>

<%= render 'form' %>

<%= link_to 'Mostrar', @articulos_factura %> |
<%= link_to 'Regresar', articulos_facturas_path %>

app/views/articulos_facturas/index.es.html.erb
<h2>Añadir artículos a la factura</h2>
<div style="display: none">
<%= i = 0 %>
</div>

<table class="table table-hover">
  <tr>
    <th>Artículo</th>
    <th>Cantidad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articulos_facturas.each do |articulos_factura| %>
  <tr>
    <td> <%= @articulos[i].nombre %></td>
    <td><%= articulos_factura.cantidad %></td>
    <td><%= link_to 'Editar', edit_articulos_factura_path(articulos_factura) %></td>
    <td><%= link_to 'Eliminar', articulos_factura, confirm: '¿Está seguro(a)?', method: :delete %></td>
  </tr>
<div style="display: none">
<%= i = i + 1 %>
</div>
<% end %>
</table>

<br />

<%= link_to 'Añadir artículo', new_articulos_factura_path %>
<%= link_to 'Continuar trámite', new_factura_path %>

app/views/articulos_facturas/index.html.erb
<h2>Añadir artículos a la factura</h2>

<table class="table table-hover">
  <tr>
    <th>Artículo</th>
    <th>Cantidad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articulos_facturas.each do |articulos_factura| %>
  <tr>
    <td><%= @articulos.each do |articulo| %>
         <%= articulo.nombre %></td>
    <% end %>
    <td><%= articulos_factura.cantidad %></td>
    <td><%= link_to 'Editar', edit_articulos_factura_path(articulos_factura) %></td>
    <td><%= link_to 'Eliminar', articulos_factura, confirm: '¿Está seguro(a)?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Añadir artículo', new_articulos_factura_path %>

app/views/articulos_facturas/new.es.html.erb
<h2>Nuevo artículo a la factura</h2>

<%= render 'form' %>

<%= button_to 'Regresar', articulos_facturas_path, :method => :get, :class => 'btn btn-primary' %>

app/views/articulos_facturas/show.es.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cantidad:</b>
  <%= @articulos_factura.cantidad %>
</p>


<%= link_to 'Editar', edit_articulos_factura_path(@articulos_factura) %> |
<%= link_to 'Regresar', articulos_facturas_path %>