config/routes.rb
Facturas::Application.routes.draw do
  resources :articulos_facturas

  resources :sucursals

  resources :facturas

  resources :clientes

  resources :articulos

  get "sesion/sesion"

  get "registro/registro"

  get "inicio/index"

  get "facturas/descarga_pdf/:id", :controller => :facturas, :action => :descarga_pdf

  match "factura/facturar" => "facturas#facturar", :as => :vista_previa, :via => :get

  devise_for :users, :controllers => { registrations: 'registro', sessions: 'sesion' }

  root :to => 'inicio#index'

end

app/models/factura.rb
class Factura < ActiveRecord::Base
  belongs_to :user
  belongs_to :cliente
  belongs_to :sucursal

  attr_accessible :cliente_id, :sucursal_id

  validates_presence_of :cliente_id, :message => "no puede quedar vacío."
  validates_presence_of :sucursal_id, :message => "no puede quedar vacío."

end

app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
  # GET /facturas
  # GET /facturas.json
  before_filter :authenticate_user!
  def index
    @facturas = Factura.all
    @facturas = current_user.facturas

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @facturas }
    end
  end

  # GET /facturas/1
  # GET /facturas/1.json
  def show
    @factura = Factura.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @factura }

    end
  end

  def descarga_pdf
    @factura = Factura.find(params[:id])
    send_file(@factura.pdf, :filename => "Factura_#{current_user.rfc}_#{@factura.folio}.pdf", :type => "application/pdf")
  end

  # GET /facturas/new
  # GET /facturas/new.json
  def new
    @factura = Factura.new
    @factura = current_user.facturas.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @factura }
    end
  end

  # GET /facturas/1/edit
  def edit
    @factura = Factura.find(params[:id])
  end
  
  # POST /facturas
  # POST /facturas.json
  def create
    @factura = Factura.new(params[:factura])
    if params[:factura][:cliente_id] == nil || params[:factura][:sucursal_id] == nil
      redirect_to :back
    else
      @factura.user_id = current_user.id
      current_user.folio = current_user.folio + 1
      current_user.save
      @factura.folio = current_user.folio.to_s.rjust(7,"0")
      @clientes = Cliente.where(:id => params[:factura][:cliente_id]).first
      @sucursals = Sucursal.where(:id => params[:factura][:sucursal_id]).first
      @articulos = Articulo.joins(:articulos_facturas).where("articulos_facturas.ip_cliente" => request.remote_ip)
      @articulos_facturas = ArticulosFactura.where(:ip_cliente => request.remote_ip, :user_id => current_user.id)
      if params[:commit] == "Generar factura"
        html = File.read("#{Rails.root}/app/views/facturas/fact.html.erb")
        plantilla = ERB.new(html)
        kit = PDFKit.new(plantilla.result(binding))
        kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/css.css"
        arch = kit.to_file("#{Rails.root}/facts/factura_#{current_user.rfc}_#{current_user.folio}.pdf")
        @factura.pdf = "#{Rails.root}/facts/factura_#{current_user.rfc}_#{current_user.folio}.pdf"
        @factura.subtotal = 0
        @factura.iva = 0
        @factura.total = 0
        @articulos_facturas.each do |articulo| 
          articulo.destroy
        end
        respond_to do |format|
          if @factura.save
            format.html { redirect_to @factura, notice: 'Factura emitida exitosamente.' }
            format.json { render json: @factura, status: :created, location: @factura }
          else
            format.html { render action: "new" }
            format.json { render json: @factura.errors, status: :unprocessable_entity }
          end
        end
      else
        current_user.folio = current_user.folio-1
        current_user.save

        respond_to do |format|
          format.html { render "factura" }
          format.json { render json: @factura }
        end

        @factura.destroy
      end
    end
  end

  # PUT /facturas/1
  # PUT /facturas/1.json
  def update
    @factura = Factura.find(params[:id])

    respond_to do |format|
      if @factura.update_attributes(params[:factura])
        format.html { redirect_to @factura, notice: 'Factura was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facturas/1
  # DELETE /facturas/1.json
  def destroy
    @factura = Factura.find(params[:id])
    @factura.destroy

    respond_to do |format|
      format.html { redirect_to facturas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/facturas_helper.rb
module FacturasHelper
  include ActionView::Helpers
end

app/views/facturas/_form.es.html.erb
<%= simple_form_for(@factura) do |f| %>
  <%= f.error_notification %>

  <% if User.find(current_user.id).sucursals == [] %>
    <%= "· No tiene sucursales agregadas." %>
  <% end %>
  <% if User.find(current_user.id).clientes == [] %>
    <br>
    <%= "·No tiene clientes agregados." %>
  <% end %>

  <div class="form-inputs">
    <%= f.association :sucursal, collection: User.find(current_user.id).sucursals, include_blank: false, :input_html => {:id => "e1" } %>
    <%= f.association :cliente, collection: User.find(current_user.id).clientes, include_blank: false, :input_html => {:id => "e2" } %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Generar factura", :class => 'btn btn-primary' %>
    <%= f.button :submit, "Vista previa", :class => 'btn btn-info'%>
  </div>
  
<% end %>

app/views/facturas/edit.es.html.erb
<h2>Editar factura</h2>

<%= render 'form' %>

<%= link_to 'Mostrar', @factura %> |
<%= link_to 'Regresar', facturas_path %>

app/views/facturas/fact.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/css.css">
    <title>Factura</title>
</head>
<body>
<% imagen= "#{Rails.root}/public"+current_user.logo_url(:thumb).to_s %>
  <div class="container">
  <header>
    <div class="emblema"><img src="<%= imagen %>" id="logo" /></div>
    <div class="datos">
    <h2><%= current_user.empresa %></h2>
    <p class="letra"><%= "#{@sucursals.calle} #{@sucursals.numexterno} #{@sucursals.numinterno}, #{@sucursals.colonia}, C.P. #{@sucursals.codpostal}" %><br><%= @sucursals.telefono %> <br><%= current_user.email %><br>México</p>
    </div>
      </div>

<div style="display: none">
<%= i = 0 %>
<%= total = 0 %>
<%= subtotal = 0 %>
<%= iva = 0 %>
</div>
      
      
    </header>
    <table class="tabla">
      <tr>
  <td >Direccion: <%= "#{@clientes.calle} #{@clientes.numexterno} #{@clientes.numinterno}, #{@clientes.colonia}, C.P. #{@clientes.codpostal}" %><br>Nombre: <%= @clientes.nombre %> <br> RFC: <%= @clientes.rfc %></td>

  
</tr>
    </table>
    <table class="tabla">
      

<tr>
  <th class="tabla">Cant.</th> 
  <th class="tabla large">Concepto</th>
  <th class="tabla">Precio</th>
  <th class="tabla">Iva</th>
  <th class="tabla">Neto</th>
  
</tr>
<% @articulos_facturas.each do |articulo| %>
<tr>
   <td class="tabla"><%= articulo.cantidad %></td> 
  <td class="tabla"><%= @articulos[i].nombre %></td>
  <td class="tabla"><%= @articulos[i].precio_u*articulo.cantidad %></td>
  <td class="tabla"><%= @articulos[i].precio_u*articulo.cantidad*0.16 %></td>
  <td class="tabla"><%= @articulos[i].precio_u*articulo.cantidad*1.16 %></td>
</tr>
<div style="display: none">
<%= total = total + @articulos[i].precio_u*articulo.cantidad*1.16 %>
<%= subtotal = subtotal + @articulos[i].precio_u*articulo.cantidad %>
<%= iva = iva + @articulos[i].precio_u*articulo.cantidad*0.16 %>
<%= i = i + 1%>
</div>
<% end %>
    </table>
    <table class="tabla">
      <tr>
        <td class="tabla letra2 alto2">Subtotal: $<%= subtotal %> <br><br><br>IVA: $<%= iva %> <br><br><br>Total: $<%= total %></td>
      </tr>
      <tr>
        <td class="tabla alto2"><img src="http://joselspovi.files.wordpress.com/2013/12/codigo-qr.jpg" width="200px" alt=""> *AQUI VA LA CADENA!*</td>
      </tr>
    </table>
  </div>
</body>
   
  
  </html>

app/views/facturas/factura.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <% content_for :head do -%>
     <%= stylesheet_link_tag 'css' %>
   <% end %>

    <title>Factura</title>
</head>
<body>
  <div class="container">
  <header>
    <div class="emblema"><%= image_tag(current_user.logo_url(:thumb).to_s) %></div>
    <div class="datos">
    <h2><%= current_user.empresa %></h2>
    <p class="letra"><%= "#{@sucursals.calle} #{@sucursals.numexterno} #{@sucursals.numinterno}, #{@sucursals.colonia}, C.P. #{@sucursals.codpostal}" %><br><%= @sucursals.telefono %> <br><%= current_user.email %><br>México</p>
    </div>
      </div>

<div style="display: none">
<%= i = 0 %>
<%= total = 0 %>
<%= subtotal = 0 %>
<%= iva = 0 %>
</div>
      
      
    </header>
    <table class="tabla">
      <tr>
  <td >Direccion: <%= "#{@clientes.calle} #{@clientes.numexterno} #{@clientes.numinterno}, #{@clientes.colonia}, C.P. #{@clientes.codpostal}" %><br>Nombre: <%= @clientes.nombre %> <br> RFC: <%= @clientes.rfc %></td>

  
</tr>
    </table>
    <table class="tabla">
      

<tr>
  <th class="tabla">Cant.</th> 
  <th class="tabla large">Concepto</th>
  <th class="tabla">Precio</th>
  <th class="tabla">Iva</th>
  <th class="tabla">Neto</th>
  
</tr>
<% @articulos_facturas.each do |articulo| %>
<tr>
   <td class="tabla"><%= articulo.cantidad %></td> 
  <td class="tabla"><%= @articulos[i].nombre %></td>
  <td class="tabla"><%= @articulos[i].precio_u*articulo.cantidad %></td>
  <td class="tabla"><%= @articulos[i].precio_u*articulo.cantidad*0.16 %></td>
  <td class="tabla"><%= @articulos[i].precio_u*articulo.cantidad*1.16 %></td>
</tr>
<div style="display: none">

<%= total = total + @articulos[i].precio_u*articulo.cantidad*1.16 %>
<%= subtotal = subtotal + @articulos[i].precio_u*articulo.cantidad %>
<%= iva = iva + @articulos[i].precio_u*articulo.cantidad*0.16 %>
<%= i = i + 1%>
</div>
<% end %>
    </table>
    <table class="tabla">
      <tr>
        <td class="tabla letra2 alto2">Subtotal: $<%= subtotal %> <br><br><br>IVA: $<%= iva %> <br><br><br>Total: $<%= total %></td>
      </tr>
      <tr>
        <td class="tabla alto2"><img src="http://joselspovi.files.wordpress.com/2013/12/codigo-qr.jpg" width="200px" alt=""> *AQUI VA LA CADENA!*</td>
      </tr>
    </table>
  </div>
</body>

<%= button_to "Regresar", new_factura_path, :class => 'btn btn-primary', :method => :get %>
   
  
  </html>


app/views/facturas/index.es.html.erb
<h2>Facturas emitidas</h2>

<table class="table table-hover">
  <tr>
    <th>Folio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @facturas.each do |factura| %>
  <tr>
    <td><%= factura.folio %></td>
    <td> <%= link_to 'Descargar factura', :action => :descarga_pdf, :id => factura.id %></td>
  </tr>
<% end %>
</table>

<br />

app/views/facturas/new.es.html.erb
<h2>Expedir factura</h2>

<%= render 'form' %>

<%= link_to 'Regresar', articulos_facturas_path %>

app/views/facturas/show.es.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Regresar', facturas_path %>