config/routes.rb
Facturas::Application.routes.draw do
  resources :articulos_facturas

  resources :sucursals

  resources :facturas

  resources :clientes

  resources :articulos

  get "sesion/sesion"

  get "registro/registro"

  get "inicio/index"

  get "facturas/descarga_pdf/:id", :controller => :facturas, :action => :descarga_pdf

  match "factura/facturar" => "facturas#facturar", :as => :vista_previa, :via => :get

  devise_for :users, :controllers => { registrations: 'registro', sessions: 'sesion' }

  root :to => 'inicio#index'

end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base

  belongs_to :user
  has_many :facturas
  belongs_to :cliente

  validates_presence_of :pseudonimo
  validates_presence_of :calle
  validates_presence_of :numexterno
  validates_presence_of :colonia
  validates_presence_of :codpostal
  validates_presence_of :delegacion
  validates_presence_of :ciudad
  validates_presence_of :estado
  validates_presence_of :telefono
  validates_format_of   :telefono, :with => /\A[0-9]{8,15}\Z/, :on => :create


  attr_accessible :pseudonimo, :calle, :numexterno, :numinterno, 
:colonia, :codpostal, :delegacion, :ciudad, :estado, :telefono


  def to_label
    "#{pseudonimo}"
  end

end

app/controllers/sucursals_controller.rb
class SucursalsController < ApplicationController
  # GET /sucursals
  # GET /sucursals.json
  before_filter :authenticate_user!
  def index
    @sucursals = Sucursal.all
    @sucursals = current_user.sucursals
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sucursals }
    end
  end

  # GET /sucursals/1
  # GET /sucursals/1.json
  def show
    @sucursal = Sucursal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sucursal }
    end
  end

  # GET /sucursals/new
  # GET /sucursals/new.json
  def new
    @sucursal = Sucursal.new
    @sucursal = current_user.sucursals.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sucursal }
    end
  end

  # GET /sucursals/1/edit
  def edit
    @sucursal = Sucursal.find(params[:id])
  end

  # POST /sucursals
  # POST /sucursals.json
  def create
    @sucursal = Sucursal.new(params[:sucursal])
    @sucursal.user_id = current_user.id

    respond_to do |format|
      if @sucursal.save
        format.html { redirect_to @sucursal, notice: 'Sucursal was successfully created.' }
        format.json { render json: @sucursal, status: :created, location: @sucursal }
      else
        format.html { render action: "new" }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sucursals/1
  # PUT /sucursals/1.json
  def update
    @sucursal = Sucursal.find(params[:id])

    respond_to do |format|
      if @sucursal.update_attributes(params[:sucursal])
        format.html { redirect_to @sucursal, notice: 'Sucursal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sucursals/1
  # DELETE /sucursals/1.json
  def destroy
    @sucursal = Sucursal.find(params[:id])
    @sucursal.destroy

    respond_to do |format|
      format.html { redirect_to sucursals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/views/sucursals/_form.es.html.erb
<%= simple_form_for(@sucursal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :pseudonimo, :required => true, :placeholder => 'Referencia a la sucursal', :label => 'Alias', :hint => 'Nombre que aparecerá al facturar para seleccionar sucursal' %>
    <%= f.input :calle, :required => true, :label => 'Calle' %>
    <%= f.input :numexterno, :required => true, :label => 'Número exterior' %>
    <%= f.input :numinterno, :required => true, :label => 'Número interior', :hint => 'De existir' %>
    <%= f.input :colonia, :required => true, :label => 'Colonia' %>
    <%= f.input :codpostal, :required => true, :label => 'Código postal' %>
    <%= f.input :delegacion, :required => true, :label => 'Delegación/Municipio' %>
    <%= f.input :ciudad, :required => true, :label => 'Ciudad' %>
    <%= f.input :estado, :required => true, :label => 'Estado' %>
    <%= f.input :telefono, :required => true, :label => 'Teléfono', :hint => 'Sin espacios, ni caracteres especiales, incluyendo clave LADA', :input_html => {:maxlength => 16} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Añadir sucursal", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/sucursals/edit.es.html.erb
<h1>Editar datos de sucursal</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @sucursal %> |
<%= link_to 'Regresar', sucursals_path %>

app/views/sucursals/index.es.html.erb
<h2>Sucursales</h2>

<table class="table table-hover">
  <tr>
    <th>Alias</th>
    <th>Calle</th>
    <th>Número exterior</th>
    <th>Número interior</th>
    <th>Colonia</th>
    <th>Código postal</th>
    <th>Delegación/Municipio</th>
    <th>Ciudad</th>
    <th>Estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sucursals.each do |sucursal| %>
  <tr>
    <td><%= sucursal.pseudonimo %></td>
    <td><%= sucursal.calle %></td>
    <td><%= sucursal.numexterno %></td>
    <td><%= sucursal.numinterno %></td>
    <td><%= sucursal.colonia %></td>
    <td><%= sucursal.codpostal %></td>
    <td><%= sucursal.delegacion %></td>
    <td><%= sucursal.ciudad %></td>
    <td><%= sucursal.estado %></td>
    <td><%= link_to 'Mostrar', sucursal %></td>
    <td><%= link_to 'Editar', edit_sucursal_path(sucursal) %></td>
    <td><%= link_to 'Eliminar', sucursal, confirm: '¿Está seguro(a)?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Añadir sucursal', new_sucursal_path %>

app/views/sucursals/new.es.html.erb
<h2>Nueva sucursal</h2>

<%= render 'form' %>

<%= button_to 'Regresar', sucursals_path, :method => :get, :class => 'btn btn-primary' %>

app/views/sucursals/show.es.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Alias:</b>
  <%= @sucursal.pseudonimo %>
</p>

<p>
  <b>Calle:</b>
  <%= @sucursal.calle %>
</p>

<p>
  <b>Número exterior:</b>
  <%= @sucursal.numexterno %>
</p>

<p>
  <b>Número interior:</b>
  <%= @sucursal.numinterno %>
</p>

<p>
  <b>Colonia:</b>
  <%= @sucursal.colonia %>
</p>

<p>
  <b>Código postal:</b>
  <%= @sucursal.codpostal %>
</p>

<p>
  <b>Delegación/Municipio:</b>
  <%= @sucursal.delegacion %>
</p>

<p>
  <b>Ciudad:</b>
  <%= @sucursal.ciudad %>
</p>

<p>
  <b>Estado:</b>
  <%= @sucursal.estado %>
</p>


<%= link_to 'Editar', edit_sucursal_path(@sucursal) %> |
<%= link_to 'Regresar', sucursals_path %>